// 简化版 wrangler.toml 配置文件
name = "gemini-api-proxy"
main = "src/worker.js"
compatibility_date = "2024-06-28"

# 开发环境配置
[dev]
port = 8787
local_protocol = "http"

# 触发器配置 - 将服务绑定到路由
[[triggers]]
type = "http"
pattern = "*/*"
